name: pdf_view
description: A fork from a flutter plugin for handling PDF files. Works on both Android, iOS ( MacOS under testing )
version: 1.0.0
homepage: https://github.com/lohanidamodar/pdf_viewer

environment:
  sdk: ^3.11.5
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
      macos:
        pluginClass: FlutterPluginPdfViewerPlugin
